"""add risk_level and findings to analysis

Revision ID: 21c0859dfd55
Revises: b29c2731f70f
Create Date: 2026-06-14 13:27:56.131755

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21c0859dfd55"
down_revision: str | Sequence[str] | None = "b29c2731f70f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    risk_level_enum = sa.Enum("LOW", "MEDIUM", "HIGH", name="risklevel")
    risk_level_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("analyses", sa.Column("risk_level", risk_level_enum, nullable=True))
    op.add_column("analyses", sa.Column("findings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "findings")
    op.drop_column("analyses", "risk_level")

    risk_level_enum = sa.Enum("LOW", "MEDIUM", "HIGH", name="risklevel")
    risk_level_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
