"""validation_check

Revision ID: b29c2731f70f
Revises: 92fd9de450a7
Create Date: 2026-06-13 18:43:29.075112

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b29c2731f70f"
down_revision: str | Sequence[str] | None = "92fd9de450a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
